### PR TITLE
Github Stars Live using API

### PR DESCRIPTION
**Pull request by rs280**
Hello Owen,

I have gotten Github Stars to work and display using the Github API.
Docker will not work because the url is not CORS enabled.
Github API limits calls to 6 per hour, but keys are free.
You might want to add one to the production environment.

Let me know if you have any questions.
Thanks,
Rishabh

### CODE REVIEW

**Comment by shyam-dev** [comment]
Nice work ! 6 per hour should be sufficient. We can add a way to limit it
even across multiple page loads.

Shyam

**Comment by ogarrett** [comment]
Does not build for me:

```
[ERROR] Docusaurus server-side rendering could not render static page with path /.


TypeError: input.replace is not a function
    at Array.reduce (<anonymous>)
[ERROR] Unable to build website for locale en.
[ERROR] Error: Failed to compile with errors.
    at /Users/owen/src/rs280/DocumentationWebsite/docs/node_modules/@docusaurus/core/lib/webpack/utils.js:180:24
    at /Users/owen/src/rs280/DocumentationWebsite/docs/node_modules/webpack/lib/MultiCompiler.js:554:14
    at processQueueWorker (/Users/owen/src/rs280/DocumentationWebsite/docs/node_modules/webpack/lib/MultiCompiler.js:491:6)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

Will investigate, but any assistance welcome, thanks!

**Comment by ogarrett** [comment]
Sorry, not quite there yet, the "build problem" appears to be a result of exceeding the request limit, and getting a 403 forbidden response.

**Comment by rs280** [comment]
Yes, you would probably have to add a key to the environment. Keys are free. You can find out more info here: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token

**Comment by ogarrett** [comment]
The issue is that unauthenticated API requests are limited to 60 requests per hour, per source IP address (source: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#requests-from-personal-accounts).  Each render of the home page generates 6 requests (5 GH buttons, plus the code above).

A personal authentication key would create its own issues: the key could be easily leaked, we would need to rotate it, and it would limit GETs to 5,000 per hour globally.

The current situation is good enough (each user has 10 page loads per hour) and there's an acceptable fallback (change https://github.com/deepfence/DocumentationWebsite/pull/20/commits/7814387bcc923dab6d8227169f18309fa9594660, GH buttons omit the number).

We should look into either of both of:
* cache the GH API calls for e.g. 60 minutes 
* converge the calls so that we just make one GET, not 6
... for a future build of the site

**Pull request merged**
